---
version: "3"

vars:
  LABELS_CONFIG_FILE: '{{.ROOT_DIR}}/.github/labels.yaml'

tasks:
  default:
    cmd: task -l
    silent: true

  append-app-labels:
    desc: Append app labels to the labels config file
    cmds:
      - for: { var: apps }
        cmd: |
          yq -i '. += [{"name": "app/{{.ITEM}}", "color": "0e8a16"}]' {{.LABELS_CONFIG_FILE}}
    vars:
      apps:
        sh: for dir in {{.ROOT_DIR}}/apps/*/; do basename "${dir}"; done
    silent: true
