---
name: Container Request
description: Request a new application to be containerized
labels: ["container-request"]

body:
  - type: markdown
    attributes:
      value: |
        Doing your due diligence and filling out this form thoroughly
        will help determine if your request shall be entertained.

  - type: input
    id: application-name
    attributes:
      label: Application Name
      description: Name of the application you would like containerized
      placeholder: e.g. Sonarr
    validations:
      required: true

  - type: input
    id: application-source-code
    attributes:
      label: Application Source Code URL
      description: URL to the source code of the application
      placeholder: e.g. https://github.com/Sonarr/Sonarr
    validations:
      required: true

  - type: dropdown
    id: application-language
    attributes:
      label: Application Language
      description: Language this application is written in
      options:
        - .Net
        - Go
        - Java
        - PHP
        - Python
        - Ruby
        - Typescript
        - Other
    validations:
      required: true

  - type: dropdown
    id: application-platforms
    attributes:
      label: Application Architectures
      description: Architectures this application supports
      multiple: true
      options:
        - linux/arm64
        - linux/amd64
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Mention anything to give further context to this container request

  - type: checkboxes
    id: self-assign
    attributes:
      label: Assign to self
      options:
        - label: I will create a PR to containerize this application myself
          required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/onedr0p/containers/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
