name: "Collect changes"
description: "Collects and stores changed files/containers"

outputs:
  changesDetected:
    description: "Whether or not changes to containers have been detected"
    value: ${{ steps.filter.outputs.addedOrModified }}
  addedOrModifiedFiles:
    description: "A list of the files changed"
    value: ${{ steps.filter.outputs.addedOrModified_files }}
  addedOrModifiedImages:
    description: "A list of the containers changed"
    value: ${{ steps.filter-containers.outputs.addedOrModifiedImages }}

runs:
  using: "composite"
  steps:
    - name: Collect changed files
      uses: dorny/paths-filter@v2
      id: filter
      with:
        list-files: json
        filters: |
          addedOrModified:
            - added|modified: 'apps/*/**'
    - name: Collect changed containers
      if: |
        steps.filter.outputs.addedOrModified == 'true'
      id: filter-containers
      shell: bash
      run: |
        PATHS='${{ steps.filter.outputs.addedOrModified_files }}'
        OUTPUT=$(echo $PATHS | jq --raw-output -c 'map(. |= split("/")[1]) | unique')
        echo "addedOrModifiedImages=${OUTPUT}" >> $GITHUB_OUTPUT
