name: Manual Release

on:
  workflow_dispatch:
    inputs:
      force:
        description: Force rebuild
        type: boolean
        default: true
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get latest runner version
        id: version
        run: |
          VERSION=$(./apps/actions-runner/ci/latest.sh)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: apps/actions-runner
          push: true
          build-args: |
            VERSION=${{ steps.version.outputs.version }}
          tags: |
            ghcr.io/${{ github.repository }}/actions-runner:latest
            ghcr.io/${{ github.repository }}/actions-runner:${{ steps.version.outputs.version }}
